---
#Install & configure Friday Demo servers
- hosts: all
  become: yes
  roles:
  - common
  vars:
    ntpserver: 0.amazon.pool.ntp.org
- hosts: webservers
  become: yes
  roles:
  - nginx
  - aws-smtp
  vars:
    whodunnit: "{{ lookup('pipe','whoami') + '@' + lookup('pipe','hostname') | quote }}"
  tags:
  - web