---
#Install & configure Friday Demo servers
- hosts: all
  become: yes
  roles:
  - goozbach.EPEL
  - common
  vars:
    ntpserver: 0.amazon.pool.ntp.org
- hosts: db
  become: yes
  roles: 
  - mariadb
  vars: 
    mariadb_root_password: blargh
  tags:
  - mariadb
- hosts: web
  become: yes
  roles:
  - nginx
  - testapp
  vars:
    whodunnit: "{{ lookup('pipe','whoami') + '@' + lookup('pipe','hostname') | quote }}"
  tags:
  - web
- hosts: lb
  become: yes
  roles: 
  - loadbalancer
  tags: 
  - lb